export type {
  AdjustInventoryStockRequest,
  CreateInventoryItemRequest,
  InventoryCategoryDto,
  InventoryItemDto,
  InventoryItemListParams,
  InventoryAdjustmentType,
  StockMovementDto,
  StockMovementListParams,
  StockMovementSortBy,
  StockMovementType,
  UpdateInventoryItemRequest,
  SortDirection,
  PaginatedResult,
} from '@gastroai/contracts';
