/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-21. Covers cryptographic auth boundary smoke checks.
interface TenantLoginResponse {
  tokens: {
    accessToken: string;
  };
}

interface PlatformLoginResponse {
  tokens: {
    accessToken: string;
  };
}

function tenantLogin(): Cypress.Chainable<TenantLoginResponse> {
  return cy
    .env<{
      apiUrl: string;
      ownerEmail: string;
      ownerPassword: string;
      tenantSlug: string;
    }>(['apiUrl', 'ownerEmail', 'ownerPassword', 'tenantSlug'])
    .then(({ apiUrl, ownerEmail, ownerPassword, tenantSlug }) =>
      cy.request<TenantLoginResponse>({
        method: 'POST',
        url: `${apiUrl}/auth/login`,
        body: { email: ownerEmail, password: ownerPassword, tenantSlug },
      }),
    )
    .then(({ body }) => cy.wrap(body));
}

function platformLogin(): Cypress.Chainable<PlatformLoginResponse> {
  return cy
    .env<{ apiUrl: string; platformEmail: string; platformPassword: string }>([
      'apiUrl',
      'platformEmail',
      'platformPassword',
    ])
    .then(({ apiUrl, platformEmail, platformPassword }) =>
      cy.request<PlatformLoginResponse>({
        method: 'POST',
        url: `${apiUrl}/platform/auth/login`,
        body: { email: platformEmail, password: platformPassword },
      }),
    )
    .then(({ body }) => cy.wrap(body));
}

describe('Auth and access boundaries', () => {
  it('rejects platform tokens on tenant APIs and tenant tokens on platform APIs', () => {
    cy.env<{ apiUrl: string }>(['apiUrl']).then(({ apiUrl }) => {
      platformLogin().then((platformAuth) => {
        cy.request({
          method: 'GET',
          url: `${apiUrl}/inventory-items`,
          headers: { Authorization: `Bearer ${platformAuth.tokens.accessToken}` },
          failOnStatusCode: false,
        }).its('status').should('be.oneOf', [401, 403]);
      });

      tenantLogin().then((tenantAuth) => {
        cy.request({
          method: 'GET',
          url: `${apiUrl}/platform/tenants`,
          headers: { Authorization: `Bearer ${tenantAuth.tokens.accessToken}` },
          failOnStatusCode: false,
        }).its('status').should('be.oneOf', [401, 403]);
      });
    });
  });

  it('does not render protected restaurant screens without a tenant session', () => {
    cy.visit('/#/cash');
    cy.contains('Iniciar sesion').should('be.visible');
    cy.contains('Entrar al restaurante').should('be.visible');
  });
});
