/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-21. Covers inventory SKU generation, product linkage, and Kardex movement smoke checks.
import { apiLogin, authHeaders, uniqueTestId } from '../support/restaurant-api';

describe('Inventory and purchases risk checks', () => {
  it('creates an ingredient with automatic SKU and writes an adjustment to Kardex', () => {
    const itemName = `Insumo ${uniqueTestId('inv')}`;
    const productName = `Producto ${uniqueTestId('prod')}`;
    const productSku = uniqueTestId('POS').toUpperCase();

    cy.intercept('GET', '**/api/v1/inventory-items*').as('getInventoryItems');
    cy.intercept('GET', '**/api/v1/inventory-categories*').as('getInventoryCategories');
    cy.intercept('GET', '**/api/v1/products*').as('getProducts');
    cy.intercept('GET', '**/api/v1/stock-movements*').as('getStockMovements');
    cy.intercept('POST', '**/api/v1/inventory-items').as('createInventoryItem');
    cy.intercept('POST', '**/api/v1/inventory-items/*/adjustments').as('adjustInventoryItem');

    apiLogin()
      .then((auth) =>
        cy.env<{ apiUrl: string }>(['apiUrl']).then(({ apiUrl }) =>
          cy.request({
            method: 'POST',
            url: `${apiUrl}/products`,
            headers: authHeaders(auth),
            body: {
              name: productName,
              sku: productSku,
              priceAmount: 9000,
              currency: 'COP',
              isActive: true,
              isSellable: true,
              isInventoried: false,
            },
          }),
        ),
      )
      .its('status')
      .should('be.oneOf', [200, 201]);

    cy.loginByApi('/inventory');
    cy.wait('@getInventoryItems').its('response.statusCode').should('eq', 200);
    cy.wait('@getInventoryCategories').its('response.body').should('have.length.greaterThan', 0);
    cy.wait('@getProducts').its('response.statusCode').should('eq', 200);
    cy.get('[data-cy="inventory-page"]').should('be.visible');

    cy.get('[data-cy="inventory-new-item"]').click();
    cy.get('[data-cy="inventory-item-dialog"]').should('be.visible');
    cy.get('[data-cy="inventory-item-sku-auto"]')
      .should('be.disabled')
      .and('have.value', 'Generacion automatica');
    cy.get('[data-cy="inventory-item-category"]').click();
    cy.get('[role="option"]').first().click();
    cy.get('body').type('{esc}');
    cy.get('[data-cy="inventory-item-name"]').type(itemName);
    cy.get('[data-cy="inventory-item-product-link"]').click();
    cy.contains('[role="option"]', productName).click();
    cy.get('[data-cy="inventory-item-unit-code"]').type('{selectall}KG');
    cy.get('[data-cy="inventory-item-unit-name"]').type('{selectall}Kilogramo');
    cy.get('[data-cy="inventory-item-initial-stock"]').type('{selectall}5');
    cy.get('[data-cy="inventory-item-initial-cost"]').type('{selectall}12000');
    cy.get('[data-cy="inventory-item-minimum-stock"]').type('{selectall}2');
    cy.get('[data-cy="inventory-item-submit"]').click();

    cy.wait('@createInventoryItem').then(({ response }) => {
      expect(response?.statusCode).to.be.oneOf([200, 201]);
      expect(response?.body.name).to.eq(itemName);
      expect(response?.body.sku).to.match(/^[A-Z]{3}-\d{4}$/);
      expect(response?.body.productName).to.eq(productName);
      expect(response?.body.productSku).to.eq(productSku);
      expect(response?.body.stockOnHand).to.eq(5);
    });
    cy.wait('@getInventoryItems');

    cy.contains('[data-cy="inventory-item-row"]', itemName)
      .scrollIntoView()
      .should('be.visible')
      .and('contain', '5 KG')
      .and('contain', productSku)
      .within(() => {
        cy.get('[data-cy="inventory-adjust-row"]').click();
      });

    cy.get('[data-cy="inventory-adjust-dialog"]').should('be.visible');
    cy.get('[data-cy="inventory-adjust-quantity"]').type('{selectall}3');
    cy.get('[data-cy="inventory-adjust-unit-cost"]').type('{selectall}13000');
    cy.get('[data-cy="inventory-adjust-reason"]').type('Conteo fisico Cypress');
    cy.get('[data-cy="inventory-adjust-submit"]').click();
    cy.wait('@adjustInventoryItem').its('response.body.stockOnHand').should('eq', 8);
    cy.wait('@getInventoryItems');

    cy.contains('[data-cy="inventory-item-row"]', itemName).scrollIntoView().should('contain', '8 KG');
    cy.wait('@getStockMovements');
    cy.contains(itemName).should('be.visible');
  });
});
