/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-21. Covers the high-risk POS and cash-register flow.
import {
  apiLogin,
  closeActiveCashSession,
  createTableAccountWithFirstProduct,
  createTestTable,
  openCashSession,
} from '../support/restaurant-api';

function tableNumber(prefix: string): string {
  return `${prefix}${Cypress._.random(1000, 9999)}${Date.now().toString().slice(-6)}`;
}

function visitPreparedAccount(number: string): void {
  cy.intercept('GET', '**/api/v1/dining-zones').as('getDiningZones');
  cy.intercept('GET', '**/api/v1/dining-tables/*/account').as('getTableAccount');

  cy.loginByApi('/tables');
  cy.wait('@getDiningZones').its('response.statusCode').should('be.oneOf', [200, 304]);
  cy.get('[data-cy="tables-page"]').should('be.visible');
  cy.contains('[data-cy="dining-table-card"]', number).click();

  cy.get('[data-cy="pos-page"]').should('be.visible');
  cy.wait('@getTableAccount').its('response.body.items').should('have.length.greaterThan', 0);
  cy.get('[data-cy="pos-order-item"]').should('exist');
}

describe('POS and cash register', () => {
  it('blocks every charge path while the cash session is closed', () => {
    const number = tableNumber('QA');

    apiLogin()
      .then((auth) =>
        closeActiveCashSession(auth)
          .then(() => createTestTable(auth, number))
          .then((table) =>
            createTableAccountWithFirstProduct(auth, table.id).then(() => cy.wrap(table)),
          ),
      )
      .then(({ number: createdNumber }) => {
        cy.intercept('GET', '**/api/v1/cash-sessions/active*').as('getActiveCash');
        visitPreparedAccount(createdNumber);

        cy.get('[data-cy="pos-charge-open"]').click();
        cy.wait('@getActiveCash').its('response.statusCode').should('eq', 404);
        cy.get('[data-cy="pos-charge-dialog"]').should('not.exist');
        cy.get('[data-cy="pos-cash-required-dialog"]')
          .should('be.visible')
          .and('contain', 'Debe abrir el turno de caja (base inicial) para poder registrar ventas');
      });
  });

  it('charges a table with cash, shows the receipt, returns to tables and releases the table', () => {
    const number = tableNumber('PX');

    apiLogin()
      .then((auth) =>
        closeActiveCashSession(auth)
          .then(() => openCashSession(auth, 100000))
          .then(() => createTestTable(auth, number))
          .then((table) =>
            createTableAccountWithFirstProduct(auth, table.id).then(() => cy.wrap(table)),
          ),
      )
      .then(({ number: createdNumber }) => {
        cy.intercept('GET', '**/api/v1/cash-sessions/active*').as('getActiveCash');
        cy.intercept('GET', '**/api/v1/table-accounts/*/command').as('getCommand');
        cy.intercept('POST', '**/api/v1/table-accounts/*/charge').as('chargeAccount');

        visitPreparedAccount(createdNumber);

        cy.get('[data-cy="pos-command"]').click();
        cy.wait('@getCommand').its('response.body.totalItems').should('be.greaterThan', 0);
        cy.get('[data-cy="pos-command-dialog"]').should('be.visible').contains('Cerrar').click();

        cy.get('[data-cy="pos-charge-open"]').click();
        cy.wait('@getActiveCash').its('response.statusCode').should('be.oneOf', [200, 304]);
        cy.get('[data-cy="pos-charge-dialog"]').should('be.visible');
        cy.get('[data-cy="pos-charge-method"]').should('contain', 'Efectivo');
        cy.get('[data-cy="pos-charge-submit"]').click();

        cy.wait('@chargeAccount').then(({ response }) => {
          expect(response?.statusCode).to.eq(201);
          expect(response?.body.paymentMethod).to.eq('CASH');
          expect(response?.body.total).to.be.greaterThan(0);
        });
        cy.get('[data-cy="pos-receipt-dialog"]').should('be.visible').contains('Cerrar').click();
        cy.location('hash').should('eq', '#/tables');
        cy.get('[data-cy="tables-page"]').should('be.visible');
        cy.contains('[data-cy="dining-table-card"]', createdNumber).should('contain', 'Libre');
      });
  });
});
