/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-21. Covers real report rendering and fixed-mock regression checks.
describe('Reports and Z report risk checks', () => {
  it('renders sales summary from the API without fixed dashboard/report mocks', () => {
    cy.intercept('GET', '**/api/v1/reports/sales-summary*').as('getSalesSummary');

    cy.loginByApi('/reports');
    cy.wait('@getSalesSummary').its('response.statusCode').should('eq', 200);

    cy.get('[data-cy="reports-page"]').should('be.visible');
    cy.contains('Reporte diario').should('be.visible');
    cy.contains('Ventas cerradas').should('be.visible');
    cy.contains('Pagos del rango').should('exist');

    cy.contains('$2.8M').should('not.exist');
    cy.contains('Reportes base').should('not.exist');
    cy.contains('Bandeja paisa ×22').should('not.exist');
  });

  it('renders dashboard from API-backed summaries instead of fixed mock labels', () => {
    cy.intercept('GET', '**/api/v1/reports/sales-summary*').as('getSalesSummary');
    cy.intercept('GET', '**/api/v1/cash-sessions/active*').as('getActiveCash');
    cy.intercept('GET', '**/api/v1/inventory-items*lowStockOnly=true*').as('getLowStock');

    cy.loginByApi('/');
    cy.wait('@getSalesSummary').its('response.statusCode').should('eq', 200);
    cy.wait('@getActiveCash');
    cy.wait('@getLowStock').its('response.statusCode').should('eq', 200);

    cy.contains('$2.8M').should('not.exist');
    cy.contains('Top del dia').should('exist');
  });
});
