/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-19. Covers the real API-backed reports screen.
describe('Reports', () => {
  it('loads the sales summary from the API without fixed mock metrics', () => {
    cy.intercept('GET', '**/api/v1/reports/sales-summary*').as('getSalesSummary');

    cy.loginByApi('/reports');
    cy.wait('@getSalesSummary').its('response.statusCode').should('eq', 200);

    cy.get('[data-cy="reports-page"]').should('be.visible');
    cy.contains('Reporte diario').should('be.visible');
    cy.contains('Ventas cerradas').should('be.visible');
    cy.contains('Pagos del rango').should('exist');

    cy.contains('$2.8M').should('not.exist');
    cy.contains('Reportes base').should('not.exist');
  });
});
