/// <reference types="cypress" />

// Generated by Cypress Author on 2026-07-01. Covers responsive shell and critical screen smoke checks.
interface ResponsiveViewport {
  name: string;
  width: number;
  height: number;
}

const RESPONSIVE_VIEWPORTS: ResponsiveViewport[] = [
  { name: 'mobile-sm', width: 360, height: 740 },
  { name: 'mobile', width: 390, height: 844 },
  { name: 'mobile-lg', width: 430, height: 932 },
  { name: 'tablet', width: 768, height: 1024 },
  { name: 'tablet-lg', width: 834, height: 1194 },
  { name: 'desktop', width: 1366, height: 768 },
  { name: 'desktop-lg', width: 1440, height: 900 },
  { name: 'wide', width: 1920, height: 1080 },
];

const RESTAURANT_SCREENS = [
  { path: '/tables', title: 'Mesas' },
  { path: '/pos', title: 'POS' },
  { path: '/inventory', title: 'Inventario' },
  { path: '/purchases', title: 'Compras' },
] as const;

function assertOperationalNavigation(viewport: ResponsiveViewport): void {
  if (viewport.width < 1024) {
    cy.get('[data-cy="mobile-nav-open"]').should('be.visible').click();
    cy.get('[data-cy="mobile-nav"]').should('be.visible');
    cy.contains('[data-cy="mobile-nav"]', 'Dashboard').should('be.visible');
    cy.contains('[data-cy="mobile-nav"]', 'Caja').should('be.visible');
    cy.get('body').type('{esc}');
    cy.get('[data-cy="mobile-nav"]').should('not.exist');
    return;
  }

  cy.get('[data-cy="mobile-nav-open"]').should('not.be.visible');
}

function appPath(path: string): string {
  return `/#${path.startsWith('/') ? path : `/${path}`}`;
}

describe('Responsive layout smoke', () => {
  RESPONSIVE_VIEWPORTS.forEach((viewport) => {
    it(`${viewport.name}: restaurant critical screens keep navigation and width stable`, () => {
      cy.setResponsiveViewport(viewport);
      cy.loginByApi(RESTAURANT_SCREENS[0].path);

      RESTAURANT_SCREENS.forEach((screen, index) => {
        if (index > 0) {
          cy.visit(appPath(screen.path));
        }
        cy.contains('h1', screen.title, { timeout: 15_000 }).should('be.visible');
        assertOperationalNavigation(viewport);
        cy.assertNoGlobalOverflow();
      });
    });

    it(`${viewport.name}: platform login keeps the admin entry usable`, () => {
      cy.setResponsiveViewport(viewport);
      cy.visit('/#/platform/login');
      cy.contains('Panel global GastroAI').should('be.visible');
      cy.contains('button', 'Entrar a plataforma').should('be.visible');
      cy.assertNoGlobalOverflow();
    });
  });
});
