/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-18. Covers real API-backed flows for purchases and employees.
interface LoginResponse {
  tokens: {
    accessToken: string;
  };
}

interface CashMovement {
  type: 'OPENING_BALANCE' | 'CASH_IN' | 'CASH_OUT' | 'SALE_PAYMENT' | 'REFUND' | 'TIP' | 'ADJUSTMENT';
  amount: number;
}

interface DiningZone {
  id: string;
}

const CASH_MOVEMENT_SIGN: Record<CashMovement['type'], 1 | -1> = {
  OPENING_BALANCE: 1,
  CASH_IN: 1,
  SALE_PAYMENT: 1,
  TIP: 1,
  ADJUSTMENT: 1,
  CASH_OUT: -1,
  REFUND: -1,
};

function apiLogin(): Cypress.Chainable<LoginResponse> {
  return cy
    .env<{
      apiUrl: string;
      ownerEmail: string;
      ownerPassword: string;
      tenantSlug: string;
    }>(['apiUrl', 'ownerEmail', 'ownerPassword', 'tenantSlug'])
    .then(({ apiUrl, ownerEmail, ownerPassword, tenantSlug }) =>
      cy.request<LoginResponse>({
        method: 'POST',
        url: `${apiUrl}/auth/login`,
        body: {
          email: ownerEmail,
          password: ownerPassword,
          tenantSlug,
        },
      }),
    )
    .then(({ body }) => cy.wrap(body));
}

function authHeaders(auth: LoginResponse): { Authorization: string } {
  return { Authorization: `Bearer ${auth.tokens.accessToken}` };
}

function closeActiveCashSession(auth: LoginResponse): Cypress.Chainable<void> {
  return cy
    .env<{ apiUrl: string }>(['apiUrl'])
    .then(({ apiUrl }) =>
      cy.request({
        method: 'GET',
        url: `${apiUrl}/cash-sessions/active`,
        headers: authHeaders(auth),
        failOnStatusCode: false,
      }),
    )
    .then((activeResponse) => {
      if (activeResponse.status === 404) {
        return cy.wrap(undefined);
      }

      const sessionId = activeResponse.body.id as string;

      return cy
        .env<{ apiUrl: string }>(['apiUrl'])
        .then(({ apiUrl }) =>
          cy.request<CashMovement[]>({
            method: 'GET',
            url: `${apiUrl}/cash-sessions/${sessionId}/movements`,
            headers: authHeaders(auth),
          }),
        )
        .then(({ body }) => {
          const countedAmount = body.reduce(
            (total, movement) => total + CASH_MOVEMENT_SIGN[movement.type] * movement.amount,
            0,
          );

          return cy
            .env<{ apiUrl: string }>(['apiUrl'])
            .then(({ apiUrl }) =>
              cy.request({
                method: 'POST',
                url: `${apiUrl}/cash-sessions/${sessionId}/close`,
                headers: authHeaders(auth),
                body: { countedAmount, notes: 'Cierre automatico Cypress' },
              }),
            )
            .then(() => undefined);
        });
    });
}

function createTestTable(
  auth: LoginResponse,
  tableNumber: string,
): Cypress.Chainable<{ number: string }> {
  return cy
    .env<{ apiUrl: string }>(['apiUrl'])
    .then(({ apiUrl }) =>
      cy.request<DiningZone[]>({
        method: 'GET',
        url: `${apiUrl}/dining-zones`,
        headers: authHeaders(auth),
      }),
    )
    .then(({ body: zones }) => {
      if (zones[0]) {
        return cy.wrap(zones[0]);
      }

      return cy
        .env<{ apiUrl: string }>(['apiUrl'])
        .then(({ apiUrl }) =>
          cy.request<DiningZone>({
            method: 'POST',
            url: `${apiUrl}/dining-zones`,
            headers: authHeaders(auth),
            body: { name: `Zona Cypress ${Date.now()}`, sortOrder: 99 },
          }),
        )
        .then(({ body }) => cy.wrap(body));
    })
    .then((zone) =>
      cy
        .env<{ apiUrl: string }>(['apiUrl'])
        .then(({ apiUrl }) =>
          cy.request({
            method: 'POST',
            url: `${apiUrl}/dining-zones/${zone.id}/tables`,
            headers: authHeaders(auth),
            body: { number: tableNumber, seats: 2 },
          }),
        )
        .then(() => cy.wrap({ number: tableNumber })),
    );
}

describe('Restaurant operations', () => {
  function uniqueId(prefix: string): string {
    return `${prefix}-${Date.now()}-${Cypress._.random(1000, 9999)}`;
  }

  it('registers and receives a purchase -> list shows the purchase as received', () => {
    const stamp = uniqueId('cy-purchase');
    const supplierName = `Proveedor ${stamp}`;
    const reference = `FC-${stamp}`;

    cy.intercept('GET', '**/api/v1/purchases*').as('getPurchases');
    cy.intercept('GET', '**/api/v1/suppliers*').as('getSuppliers');
    cy.intercept('POST', '**/api/v1/suppliers').as('createSupplier');
    cy.intercept('POST', '**/api/v1/purchases').as('createPurchase');
    cy.intercept('PATCH', '**/api/v1/purchases/*/receive').as('receivePurchase');

    cy.loginByApi('/purchases');
    cy.wait('@getPurchases');
    cy.get('[data-cy="purchases-page"]').should('be.visible');

    cy.get('[data-cy="purchases-new-supplier"]').click();
    cy.get('[data-cy="supplier-name"]').type(supplierName);
    cy.get('[data-cy="supplier-document"]').type(`900${Cypress._.random(100000, 999999)}`);
    cy.get('[data-cy="supplier-email"]').type(`${stamp}@gastroia.test`);
    cy.get('[data-cy="supplier-phone"]').type('3001234567');
    cy.get('[data-cy="supplier-submit"]').click();
    cy.wait('@createSupplier').its('response.statusCode').should('be.oneOf', [200, 201]);

    cy.get('[data-cy="purchases-new-purchase"]').click();
    cy.get('[data-cy="purchase-supplier-select"]').click();
    cy.contains('[role="option"]', supplierName).click();
    cy.get('[data-cy="purchase-reference"]').type(reference);
    cy.get('[data-cy="purchase-item-name"]').type('Carne molida Cypress');
    cy.get('[data-cy="purchase-quantity"]').type('{selectall}2').should('have.value', '2');
    cy.get('[data-cy="purchase-unit-cost"]').type('{selectall}10000').should('have.value', '10000');
    cy.get('[data-cy="purchase-tax-total"]').type('{selectall}1900').should('have.value', '1900');
    cy.get('[data-cy="purchase-submit"]').click();
    cy.wait('@createPurchase').its('response.body').should('include', {
      status: 'DRAFT',
      total: 21900,
    });
    cy.intercept('GET', '**/api/v1/purchases*search=*').as('searchPurchases');
    cy.get('[data-cy="purchases-search"]').clear().type(supplierName);
    cy.wait('@searchPurchases');

    cy.contains('[data-cy="purchase-row"]', supplierName)
      .should('be.visible')
      .and('contain', 'Por recibir')
      .within(() => {
        cy.get('[data-cy="purchase-receive"]').click();
      });

    cy.contains('Recibir compra').should('be.visible');
    cy.get('[data-cy="purchase-confirm-action"]').click();
    cy.wait('@receivePurchase').its('response.body.status').should('eq', 'RECEIVED');

    cy.contains('[data-cy="purchase-row"]', supplierName).should('contain', 'Recibida');
  });

  it('creates and suspends an employee -> access state updates in the card', () => {
    const stamp = uniqueId('cy-employee');
    const fullName = `Empleado ${stamp}`;
    const email = `${stamp}@gastroia.test`;

    cy.intercept('GET', '**/api/v1/employees*').as('getEmployees');
    cy.intercept('POST', '**/api/v1/employees').as('createEmployee');
    cy.intercept('PATCH', '**/api/v1/employees/*/access').as('updateEmployeeAccess');

    cy.loginByApi('/employees');
    cy.wait('@getEmployees');
    cy.get('[data-cy="employees-page"]').should('be.visible');

    cy.get('[data-cy="employees-new"]').click();
    cy.get('[data-cy="employee-full-name"]').type(fullName);
    cy.get('[data-cy="employee-email"]').type(email);
    cy.get('[data-cy="employee-temporary-password"]').type('Temporal123!');
    cy.get('[data-cy="employee-submit"]').click();
    cy.wait('@createEmployee').its('response.statusCode').should('be.oneOf', [200, 201]);

    cy.contains('[data-cy="employee-card"]', email)
      .should('be.visible')
      .and('contain', 'Acceso activo')
      .within(() => {
        cy.get('[data-cy="employee-toggle-access"]').click();
      });

    cy.wait('@updateEmployeeAccess').its('response.body.isActive').should('eq', false);
    cy.contains('[data-cy="employee-card"]', email).should('contain', 'Acceso suspendido');
  });

  it('opens cash, charges a table and closes cash -> Z report reflects the sale', () => {
    const tableNumber = `CY${Cypress._.random(1000, 9999)}${Date.now().toString().slice(-6)}`;

    apiLogin()
      .then((auth) => closeActiveCashSession(auth).then(() => createTestTable(auth, tableNumber)))
      .then(({ number }) => {
        cy.intercept('GET', '**/api/v1/cash-sessions/active').as('getActiveCash');
        cy.intercept('POST', '**/api/v1/cash-sessions').as('openCash');

        cy.loginByApi('/cash');
        cy.wait('@getActiveCash');
        cy.get('[data-cy="cash-page"]').should('be.visible');
        cy.get('[data-cy="cash-open-dialog"]').click();
        cy.get('[data-cy="cash-opening-balance"]').clear().type('100000');
        cy.get('[data-cy="cash-open-submit"]').click();
        cy.wait('@openCash').its('response.statusCode').should('be.oneOf', [200, 201]);

        cy.intercept('GET', '**/api/v1/dining-zones').as('getDiningZones');
        cy.intercept('POST', '**/api/v1/dining-tables/*/account').as('openAccount');
        cy.intercept('POST', '**/api/v1/table-accounts/*/items').as('addItem');
        cy.intercept('GET', '**/api/v1/table-accounts/*/command').as('getCommand');
        cy.intercept('POST', '**/api/v1/table-accounts/*/charge').as('chargeAccount');

        cy.loginByApi('/tables');
        cy.wait('@getDiningZones');
        cy.get('[data-cy="tables-page"]').should('be.visible');
        cy.contains('[data-cy="dining-table-card"]', number).click();

        cy.get('[data-cy="pos-page"]').should('be.visible');
        cy.get('[data-cy="pos-open-account"]').click();
        cy.wait('@openAccount').its('response.statusCode').should('be.oneOf', [200, 201]);
        cy.get('[data-cy="pos-product-card"]').first().click();
        cy.wait('@addItem').its('response.body.items').should('have.length.greaterThan', 0);
        cy.get('[data-cy="pos-order-item"]').should('exist');

        cy.get('[data-cy="pos-command"]').click();
        cy.wait('@getCommand').its('response.body.totalItems').should('be.greaterThan', 0);
        cy.get('[data-cy="pos-command-dialog"]').should('be.visible').contains('Cerrar').click();

        cy.get('[data-cy="pos-charge-open"]').click();
        cy.get('[data-cy="pos-charge-dialog"]').should('be.visible');
        cy.get('[data-cy="pos-charge-method"]').click();
        cy.contains('[role="option"]', 'Efectivo').click();
        cy.get('[data-cy="pos-charge-submit"]').click();
        cy.wait('@chargeAccount').then(({ response }) => {
          expect(response?.statusCode).to.eq(201);
          expect(response?.body.paymentMethod).to.eq('CASH');
          expect(response?.body.total).to.be.greaterThan(0);
        });
        cy.get('[data-cy="pos-receipt-dialog"]').should('be.visible').contains('Cerrar').click();

        cy.loginByApi('/tables');
        cy.wait('@getDiningZones');
        cy.contains('[data-cy="dining-table-card"]', number).should('contain', 'Libre');

        cy.intercept('POST', '**/api/v1/cash-sessions/*/close').as('closeCash');
        cy.intercept('GET', '**/api/v1/cash-sessions/*/z-report').as('getZReport');

        cy.loginByApi('/cash');
        cy.wait('@getActiveCash');
        cy.get('[data-cy="cash-close-open"]').click();
        cy.get('[data-cy="cash-close-submit"]').click();
        cy.wait('@closeCash').its('response.body.status').should('eq', 'CLOSED');
        cy.wait('@getZReport').then(({ response }) => {
          expect(response?.statusCode).to.eq(200);
          expect(response?.body.ticketCount).to.be.greaterThan(0);
          expect(response?.body.totalSales).to.be.greaterThan(0);
          expect(response?.body.byMethod.some((entry: { method: string }) => entry.method === 'CASH')).to.eq(
            true,
          );
        });
        cy.get('[data-cy="cash-z-report-dialog"]').should('be.visible').and('contain', 'Reporte Z');
      });
  });
});
