/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-18. Covers real API-backed flows for purchases and employees.
describe('Restaurant operations', () => {
  function uniqueId(prefix: string): string {
    return `${prefix}-${Date.now()}-${Cypress._.random(1000, 9999)}`;
  }

  it('registers and receives a purchase -> list shows the purchase as received', () => {
    const stamp = uniqueId('cy-purchase');
    const supplierName = `Proveedor ${stamp}`;
    const reference = `FC-${stamp}`;

    cy.intercept('GET', '**/api/v1/purchases*').as('getPurchases');
    cy.intercept('GET', '**/api/v1/suppliers*').as('getSuppliers');
    cy.intercept('POST', '**/api/v1/suppliers').as('createSupplier');
    cy.intercept('POST', '**/api/v1/purchases').as('createPurchase');
    cy.intercept('PATCH', '**/api/v1/purchases/*/receive').as('receivePurchase');

    cy.loginByApi('/purchases');
    cy.wait('@getPurchases');
    cy.get('[data-cy="purchases-page"]').should('be.visible');

    cy.get('[data-cy="purchases-new-supplier"]').click();
    cy.get('[data-cy="supplier-name"]').type(supplierName);
    cy.get('[data-cy="supplier-document"]').type(`900${Cypress._.random(100000, 999999)}`);
    cy.get('[data-cy="supplier-email"]').type(`${stamp}@gastroia.test`);
    cy.get('[data-cy="supplier-phone"]').type('3001234567');
    cy.get('[data-cy="supplier-submit"]').click();
    cy.wait('@createSupplier').its('response.statusCode').should('be.oneOf', [200, 201]);

    cy.get('[data-cy="purchases-new-purchase"]').click();
    cy.get('[data-cy="purchase-supplier-select"]').click();
    cy.contains('[role="option"]', supplierName).click();
    cy.get('[data-cy="purchase-reference"]').type(reference);
    cy.get('[data-cy="purchase-item-name"]').type('Carne molida Cypress');
    cy.get('[data-cy="purchase-quantity"]').type('{selectall}2').should('have.value', '2');
    cy.get('[data-cy="purchase-unit-cost"]').type('{selectall}10000').should('have.value', '10000');
    cy.get('[data-cy="purchase-tax-total"]').type('{selectall}1900').should('have.value', '1900');
    cy.get('[data-cy="purchase-submit"]').click();
    cy.wait('@createPurchase').its('response.body').should('include', {
      status: 'DRAFT',
      total: 21900,
    });

    cy.contains('[data-cy="purchase-row"]', reference)
      .should('be.visible')
      .and('contain', 'Por recibir')
      .within(() => {
        cy.get('[data-cy="purchase-receive"]').click();
      });

    cy.contains('Recibir compra').should('be.visible');
    cy.get('[data-cy="purchase-confirm-action"]').click();
    cy.wait('@receivePurchase').its('response.body.status').should('eq', 'RECEIVED');

    cy.contains('[data-cy="purchase-row"]', reference).should('contain', 'Recibida');
  });

  it('creates and suspends an employee -> access state updates in the card', () => {
    const stamp = uniqueId('cy-employee');
    const fullName = `Empleado ${stamp}`;
    const email = `${stamp}@gastroia.test`;

    cy.intercept('GET', '**/api/v1/employees*').as('getEmployees');
    cy.intercept('POST', '**/api/v1/employees').as('createEmployee');
    cy.intercept('PATCH', '**/api/v1/employees/*/access').as('updateEmployeeAccess');

    cy.loginByApi('/employees');
    cy.wait('@getEmployees');
    cy.get('[data-cy="employees-page"]').should('be.visible');

    cy.get('[data-cy="employees-new"]').click();
    cy.get('[data-cy="employee-full-name"]').type(fullName);
    cy.get('[data-cy="employee-email"]').type(email);
    cy.get('[data-cy="employee-temporary-password"]').type('Temporal123!');
    cy.get('[data-cy="employee-submit"]').click();
    cy.wait('@createEmployee').its('response.statusCode').should('be.oneOf', [200, 201]);

    cy.contains('[data-cy="employee-card"]', email)
      .should('be.visible')
      .and('contain', 'Acceso activo')
      .within(() => {
        cy.get('[data-cy="employee-toggle-access"]').click();
      });

    cy.wait('@updateEmployeeAccess').its('response.body.isActive').should('eq', false);
    cy.contains('[data-cy="employee-card"]', email).should('contain', 'Acceso suspendido');
  });
});
