/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-20. Covers the SaaS platform login and tenant creation smoke flow.
interface PlatformLoginResponse {
  tokens: {
    accessToken: string;
    refreshToken: string;
  };
}

interface PlatformTenantResponse {
  id: string;
  name: string;
  planCode: string | null;
  status: string;
}

interface TenantLoginResponse {
  tokens: {
    accessToken: string;
  };
}

function appPath(path: string): string {
  return `/#${path.startsWith('/') ? path : `/${path}`}`;
}

describe('SaaS platform', () => {
  it('creates a tenant and controls SaaS access without operating fiscal data', () => {
    const stamp = `${Date.now()}-${Cypress._.random(1000, 9999)}`;
    const tenantName = `Cypress Restaurante ${stamp}`;
    const ownerEmail = `owner-${stamp}@gastroia.test`;
    let platformToken = '';

    cy.intercept('POST', '**/api/v1/platform/auth/login').as('platformLogin');
    cy.intercept('GET', '**/api/v1/platform/tenants').as('platformTenants');
    cy.intercept('POST', '**/api/v1/platform/tenants').as('platformCreateTenant');

    cy.env<{ platformEmail: string; platformPassword: string }>([
      'platformEmail',
      'platformPassword',
    ]).then(({ platformEmail, platformPassword }) => {
      cy.visit(appPath('/platform/login'));
      cy.get('[data-cy="platform-login-form"]').should('be.visible');
      cy.get('[data-cy="platform-email"]').clear().type(platformEmail);
      cy.get('[data-cy="platform-password"]').clear().type(platformPassword);
      cy.get('[data-cy="platform-login-submit"]').click();
    });

    cy.wait('@platformLogin')
      .its('response.body')
      .should((body: PlatformLoginResponse) => {
        platformToken = body.tokens.accessToken;
        expect(body.tokens.accessToken).to.be.a('string').and.not.be.empty;
      });
    cy.location('hash').should('eq', '#/platform');

    cy.visit(appPath('/platform/tenants'));
    cy.wait('@platformTenants').its('response.statusCode').should('eq', 200);
    cy.get('[data-cy="platform-new-tenant"]').should('be.visible');

    cy.get('[data-cy="platform-new-tenant"]').click();
    cy.get('[data-cy="platform-tenant-form"]').should('be.visible');
    cy.get('[data-cy="platform-tenant-name"]').type(tenantName);
    cy.get('[data-cy="platform-tenant-nit"]').should('not.exist');
    cy.get('[data-cy="platform-tenant-municipality"]').should('not.exist');
    cy.get('[data-cy="platform-tenant-fiscal-responsibility"]').should('not.exist');
    cy.get('[data-cy="platform-tenant-branch-city"]').type('Bogota');
    cy.get('[data-cy="platform-tenant-owner-email"]').type(ownerEmail);
    cy.get('[data-cy="platform-tenant-owner-name"]').type('Owner Cypress');
    cy.get('[data-cy="platform-tenant-owner-password"]').type('Temporal123!');
    cy.get('[data-cy="platform-tenant-branch-name"]').clear().type('Principal');
    cy.get('[data-cy="platform-tenant-branch-code"]').clear().type('MAIN');
    cy.get('[data-cy="platform-tenant-branch-address"]').type('Cra 1 # 2-3');
    cy.get('[data-cy="platform-tenant-branch-phone"]').type('3001234567');
    cy.get('[data-cy="platform-tenant-submit"]').click();

    cy.wait('@platformCreateTenant').then(({ response }) => {
      const tenant = response?.body as PlatformTenantResponse;
      expect(tenant.name).to.eq(tenantName);
      expect(tenant.planCode).to.eq('BASIC');
      expect(tenant.status).to.eq('ACTIVE');
      cy.env<{ apiUrl: string }>(['apiUrl']).then(({ apiUrl }) => {
        cy.request({
          method: 'GET',
          url: `${apiUrl}/platform/tenants/${tenant.id}`,
          headers: { Authorization: `Bearer ${platformToken}` },
        })
          .its('body.features')
          .should((features: Array<{ code: string; enabled: boolean }>) => {
            expect(features.find((feature) => feature.code === 'dian.enabled')?.enabled).to.eq(
              true,
            );
          });

        cy.request({
          method: 'GET',
          url: `${apiUrl}/platform/tenants/${tenant.id}/fiscal/documents`,
          headers: { Authorization: `Bearer ${platformToken}` },
          failOnStatusCode: false,
        })
          .its('status')
          .should('eq', 404);
      });

      cy.visit(appPath(`/platform/tenants/${tenant.id}`));
      cy.get('body').should('contain.text', 'Facturacion electronica DIAN: habilitada');
      cy.get('[role="tablist"]').should('not.contain.text', 'Facturacion');
      cy.get('body').should('not.contain.text', 'NIT');
      cy.visit(appPath('/platform/tenants'));
    });
    cy.wait('@platformTenants');
    cy.contains('[data-cy="platform-tenant-row"]', tenantName)
      .should('be.visible')
      .and('contain', 'BASIC')
      .and('contain', 'Activo');

    cy.intercept('PATCH', '**/api/v1/platform/tenants/*/status').as('updateTenantStatus');
    cy.contains('[data-cy="platform-tenant-row"]', tenantName)
      .find('[data-cy="platform-tenant-status-action"]')
      .click();
    cy.get('[data-cy="platform-tenant-status-confirm"]').click();
    cy.wait('@updateTenantStatus').its('response.body.status').should('eq', 'SUSPENDED');

    cy.env<{ apiUrl: string }>(['apiUrl']).then(({ apiUrl }) => {
      cy.request<TenantLoginResponse>({
        method: 'POST',
        url: `${apiUrl}/auth/login`,
        body: {
          tenantIdentifier: tenantName,
          email: ownerEmail,
          password: 'Temporal123!',
        },
      }).then(({ body }) => {
        cy.request({
          method: 'GET',
          url: `${apiUrl}/inventory-items`,
          headers: { Authorization: `Bearer ${body.tokens.accessToken}` },
          failOnStatusCode: false,
        })
          .its('status')
          .should('eq', 403);
      });
    });

    cy.contains('[data-cy="platform-tenant-row"]', tenantName)
      .find('[data-cy="platform-tenant-status-action"]')
      .click();
    cy.get('[data-cy="platform-tenant-status-confirm"]').click();
    cy.wait('@updateTenantStatus').its('response.body.status').should('eq', 'ACTIVE');

    cy.intercept('GET', '**/api/v1/platform/tenants/*/features').as('getTenantFeatures');
    cy.intercept('PATCH', '**/api/v1/platform/tenants/*/features/inventory.enabled').as(
      'disableInventory',
    );
    cy.visit(appPath('/platform/features'));
    cy.get('[data-cy="platform-feature-tenant-select"]').click();
    cy.contains('[role="option"]', tenantName).click();
    cy.get('body').type('{esc}');
    cy.wait('@getTenantFeatures');
    cy.get('[data-cy="platform-feature-toggle-inventory.enabled"]').click();
    cy.get('[data-cy="platform-feature-disable-reason"]').type('Bloqueo Cypress de inventario');
    cy.get('[data-cy="platform-feature-disable-confirm"]').click();
    cy.wait('@disableInventory').its('response.body').should('be.an', 'array');

    cy.env<{ apiUrl: string }>(['apiUrl']).then(({ apiUrl }) => {
      cy.request<TenantLoginResponse>({
        method: 'POST',
        url: `${apiUrl}/auth/login`,
        body: {
          tenantIdentifier: tenantName,
          email: ownerEmail,
          password: 'Temporal123!',
        },
      }).then(({ body }) => {
        cy.request({
          method: 'GET',
          url: `${apiUrl}/inventory-items`,
          headers: { Authorization: `Bearer ${body.tokens.accessToken}` },
          failOnStatusCode: false,
        })
          .its('status')
          .should('eq', 403);
      });
    });
  });
});
