/// <reference types="cypress" />

// Generated by Cypress Author on 2026-06-20. Covers the SaaS platform login and tenant creation smoke flow.
interface PlatformLoginResponse {
  tokens: {
    accessToken: string;
    refreshToken: string;
  };
}

interface PlatformTenantResponse {
  id: string;
  name: string;
  slug: string;
  planCode: string | null;
  status: string;
}

function appPath(path: string): string {
  return `/#${path.startsWith('/') ? path : `/${path}`}`;
}

describe('SaaS platform', () => {
  it('logs in, lists tenants and creates a BASIC tenant', () => {
    const stamp = `${Date.now()}-${Cypress._.random(1000, 9999)}`;
    const tenantName = `Cypress Restaurante ${stamp}`;
    const tenantSlug = `cy-rest-${stamp}`;
    const ownerEmail = `owner-${stamp}@gastroia.test`;

    cy.intercept('POST', '**/api/v1/platform/auth/login').as('platformLogin');
    cy.intercept('GET', '**/api/v1/platform/overview').as('platformOverview');
    cy.intercept('GET', '**/api/v1/platform/tenants').as('platformTenants');
    cy.intercept('POST', '**/api/v1/platform/tenants').as('platformCreateTenant');

    cy.env<{ platformEmail: string; platformPassword: string }>([
      'platformEmail',
      'platformPassword',
    ]).then(({ platformEmail, platformPassword }) => {
      cy.visit(appPath('/platform/login'));
      cy.get('[data-cy="platform-login-form"]').should('be.visible');
      cy.get('[data-cy="platform-email"]').clear().type(platformEmail);
      cy.get('[data-cy="platform-password"]').clear().type(platformPassword);
      cy.get('[data-cy="platform-login-submit"]').click();
    });

    cy.wait('@platformLogin')
      .its('response.body')
      .should((body: PlatformLoginResponse) => {
        expect(body.tokens.accessToken).to.be.a('string').and.not.be.empty;
      });
    cy.wait('@platformOverview').its('response.statusCode').should('eq', 200);
    cy.contains('Overview global').should('be.visible');

    cy.visit(appPath('/platform/tenants'));
    cy.wait('@platformTenants').its('response.statusCode').should('eq', 200);
    cy.contains('Tenants').should('be.visible');

    cy.get('[data-cy="platform-new-tenant"]').click();
    cy.get('[data-cy="platform-tenant-form"]').should('be.visible');
    cy.get('[data-cy="platform-tenant-name"]').type(tenantName);
    cy.get('[data-cy="platform-tenant-slug"]').type(tenantSlug);
    cy.get('[data-cy="platform-tenant-owner-email"]').type(ownerEmail);
    cy.get('[data-cy="platform-tenant-owner-name"]').type('Owner Cypress');
    cy.get('[data-cy="platform-tenant-owner-password"]').type('Temporal123!');
    cy.get('[data-cy="platform-tenant-branch-name"]').clear().type('Principal');
    cy.get('[data-cy="platform-tenant-branch-code"]').clear().type('MAIN');
    cy.get('[data-cy="platform-tenant-submit"]').click();

    cy.wait('@platformCreateTenant')
      .its('response.body')
      .should((tenant: PlatformTenantResponse) => {
        expect(tenant.name).to.eq(tenantName);
        expect(tenant.slug).to.eq(tenantSlug);
        expect(tenant.planCode).to.eq('BASIC');
        expect(tenant.status).to.eq('ACTIVE');
      });
    cy.wait('@platformTenants');
    cy.contains('[data-cy="platform-tenant-row"]', tenantName)
      .should('be.visible')
      .and('contain', 'BASIC')
      .and('contain', 'ACTIVE');
  });
});
