export type {
  CreateFiscalCreditNotePayload,
  FiscalDocumentActionDto,
  FiscalDocumentDetailDto,
  FiscalDocumentDto,
  FiscalDocumentListDto,
  FiscalNumberingRangeDto,
  FiscalNumberingRangeListDto,
  FiscalCreditNoteActionDto,
  FiscalCreditNoteDto,
  FiscalInvoiceStatus,
  FiscalProfileDto,
  FactusConnectionDto,
  FactusConnectionStatus,
  FactusEnvironment,
  UpsertFactusConnectionPayload,
  BranchFiscalConfigurationDto,
  UpsertBranchFiscalConfigurationPayload,
  UpsertFiscalProfilePayload,
} from '@gastroai/contracts';
